services:  
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    volumes:
      - ./data/db:/data/db
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_URL: mongodb://root:pass@mongo:27017/
  
  delivery-service:
    build: .
    container_name: delivery-service
    volumes:
      - ./uploads:/app/uploads
    ports: 
      - 8989:8989
    environment: 
      - HTTP_PORT=8989
      - MONGO_URL=mongodb://root:pass@mongo:27017/
    depends_on:
      - mongo
      